version: 2
updates:
  # We can't use yaml anchors (or another way to reuse the common configuration), so there's some repetetiveness to the
  # array elements provided here, as (right now) we just want the same config, but for every .csproj in the project.
  - directory: "/src/TestUtilities.Scenarios"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
    assignees:
      - "ehonda"
    open-pull-requests-limit: 5

  - directory: "/tests/TestUtilities.Scenarios.Tests"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
    assignees:
      - "ehonda"
    open-pull-requests-limit: 5

  - directory: "/samples/Examples/Examples.Common"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
    assignees:
      - "ehonda"
    open-pull-requests-limit: 5

  - directory: "/samples/Examples/Examples.MSTest"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
    assignees:
      - "ehonda"
    open-pull-requests-limit: 5

  - directory: "/samples/Examples/Examples.NUnit"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
    assignees:
      - "ehonda"
    open-pull-requests-limit: 5

  - directory: "/samples/Examples/Examples.XUnit"
    package-ecosystem: "nuget"
    schedule:
      interval: "daily"
    assignees:
      - "ehonda"
    open-pull-requests-limit: 5
