#!/bin/bash

set -euo pipefail

usage() {
    cat <<EOF
Usage: showcase TYPE
    TYPE must be 'raw' or 'scenario'
EOF
}

validate_showcase_type() {
    local type=$1
    if [[ "$type" != "raw" && "$type" != "scenario" ]]; then
        usage
        exit 1
    fi
}

run_tests() {
    local type=$1
    # Redirecting stderr to filter out failure messages from XUnit
    # that we don't want in the output
    dotnet test --filter "$type" 2>/dev/null | grep "Failed "
}

main() {
    local type=$1
    validate_showcase_type "$type"
    run_tests "$type"
}

# Entrypoint
# Default $1 if unset to get to usage validation and handle it there
main "${1:-}"
